@url = http://192.168.1.229:8090


### create todo
POST {{url}}/api/todo/
Accept: application/json
Content-Type: application/json

{
    "task":"running"
}

### update todo
PUT {{url}}/api/todo/{id}
Accept: application/json
Content-Type: application/json

{
    "task":"new running"
}

### get one todo
GET {{url}}/api/todo/
Accept: application/json
Content-Type: application/json


### list todos
GET {{url}}/api/todo/
Accept: application/json
Content-Type: application/json


### delete one todo
DELETE {{url}}/api/todo/{id}
Accept: application/json
Content-Type: application/json
